### ISSUE TITLE
New release generated every day, despite no changes

### ISSUE THREAD

**Issue by jenspinney** [cloudfoundry-incubator/eirinifs#5]
It seems like there's a new major version of eirinifs in the GitHub releases section every day, despite no new changes. Versions 35-46 all point to the same Git SHA.

**Comment by alex-slynko** [comment]
Hi @jenspinney 

We cut the new `eirinifs` release for [each cflinuxfs3 release](https://github.com/cloudfoundry/cflinuxfs3/releases). We will probably add the correspondent `cflinuxfs3` release version to the `eirinifs` release page.

**Comment by gdankov** [comment]
To add to what Alex said, now you can also see the tag and digest of the `cflinuxfs3` image, which was used to cut the `eirinifs` release, in the release notes of `eirinifs`.
