### ISSUE TITLE
Checksum for release files

### ISSUE THREAD

**Issue by jimmykarily** [cloudfoundry-incubator/eirinifs#6]
To be able to consume eirinifs (https://github.com/cloudfoundry-community/eirini-bosh-release/blob/master/config/blobs.yml#L1) we need to be able to verify that the file we got from GitHub releases page is correct and not tampered with. For this we will need a checksum to compare against. The checksum currently in the release description matches the cflinuxfs3 image which is not even included in the release files.

Ideally every downloadable file in the release should have a checksum in the description. Since GitHub generates the `Source code` files automatically, it is ok to only have a checksum for the `eirinifs.tar` file.

**Comment by gdankov** [comment]
Hey @jimmykarily,

The shasum is now published as an asset alongside `eirinifs.tar`.

**Comment by jimmykarily** [comment]
Great thanks!
